CREATE TABLE CREDIT( 
  id               INTEGER   PRIMARY KEY autoincrement,
  source           TEXT      NOT NULL,
  transaction_date DATETIME  NOT NULL,
  bookkeeping_date DATETIME  NOT NULL,
  card_id          TEXT      NOT NULL,
 transaction_money NUMERIC   NOT NULL default 0,
  balance_currency TEXT      NOT NULL,
  balance_money    NUMERIC   NOT NULL default 0,
  transaction_desc TEXT      NOT NULL,
  payment_type_id  TEXT      NOT NULL,
 payment_type_name TEXT      NOT NULL,
  card_type_id     INTEGER   NOT NULL default 1,
  card_type_name   TEXT      NOT NULL default 'Credit Card',
  deleted          INTEGER   NOT NULL default 0,
  consumption_name TEXT      NOT NULL,
  consumption_id INTEGER     NOT NULL,
  consume_name     TEXT      NOT NULL,
  consume_id       TEXT      NOT NULL,
  keyword          TEXT      NOT NULL,
  demoarea         TEXT      NOT NULL,
  recordid         TEXT      default 'no record id',
  version          INTEGER   default 0,
  createuser       TEXT      default 'system',
  createtime       DATETIME  default (datetime('now', 'localtime')),
  updateuser       TEXT      default 'system',
  updatetime       DATETIME  default (datetime('now', 'localtime'))
);